### ISSUE TITLE
Several problems 

### ISSUE THREAD

**Issue by FgfdCBVCbnsebtgf** [devfacet/iptocountry#2]
Hello,

1) When i make:
ippais = require('iptocountry');
ippais.ipSearch(["89.181.115.165"]);

gives:
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.ipSearch (/servidor_html/sementes.gratis/s/node_modules/iptocountry/lib/iptocountry.js:187:133)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)

2) The site to retrieve the IpToCountry.csv.gz does not allow too many requests per hour. As a developer i need to make tests an in my code i start the node application checking for the update of IpToCountry.csv.gz. The problem is that iptocountry does not handle the gzip error. The site allows the donwload of IpToCountry.csv.gz but inside is a HTML file. So i get an error very often

**Comment by ghost** [comment]
@FgfdCBVCbnsebtgf 

Regarding `1.`, check my fork. I've fixed the issue.

Regarding `2.`, you really should not be downloading the file too often. You're abusing what is a free service (donationware). We're checking for updates every 48 hours, and it's been fine 99.9% of the times.
